# Generated by Django 5.0.3 on 2026-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icfes_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InglesAnalisisIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nacional", "Nacional"),
                            ("departamento", "Departamental"),
                        ],
                        default="nacional",
                        max_length=20,
                    ),
                ),
                ("parametro", models.CharField(blank=True, default="", max_length=100)),
                ("ano_referencia", models.IntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("archivado", "Archivado")],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("analisis_md", models.TextField()),
                ("situacion", models.TextField(blank=True)),
                ("geografia", models.TextField(blank=True)),
                ("prediccion", models.TextField(blank=True)),
                ("brecha", models.TextField(blank=True)),
                ("recomendacion", models.TextField(blank=True)),
                (
                    "modelo_ia",
                    models.CharField(default="claude-sonnet-4-6", max_length=100),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("tokens_input", models.IntegerField(blank=True, null=True)),
                ("tokens_output", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Análisis IA - Inglés",
                "verbose_name_plural": "Análisis IA - Inglés",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "parametro", "ano_referencia", "estado"],
                        name="icfes_dashb_tipo_113540_idx",
                    )
                ],
            },
        ),
    ]
