# Generated by Django 5.0.3 on 2026-03-02 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icfes_dashboard", "0002_add_ingles_analisis_ia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "lote",
                    models.IntegerField(
                        default=1, help_text="Número de lote (1, 2, 3...)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activa", "Activa"),
                            ("pausada", "Pausada"),
                            ("completada", "Completada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Segmento objetivo, estrategia, notas"
                    ),
                ),
                (
                    "email_remitente",
                    models.EmailField(default="icfes@sabededatos.com", max_length=254),
                ),
                (
                    "nombre_remitente",
                    models.CharField(
                        default="Jose Maestre",
                        help_text="Nombre que ve el destinatario. Para Tier 1 usar nombre personal.",
                        max_length=100,
                    ),
                ),
                (
                    "ciudades_objetivo",
                    models.TextField(
                        blank=True, help_text="Ciudades incluidas, separadas por coma"
                    ),
                ),
                (
                    "top_n_por_ciudad",
                    models.IntegerField(
                        default=10, help_text="Top N colegios por ciudad"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_lanzamiento", models.DateTimeField(blank=True, null=True)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Campaña",
                "verbose_name_plural": "Campañas",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="CampaignProspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_colegio", models.CharField(max_length=255)),
                ("rector", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("municipio", models.CharField(max_length=100)),
                ("departamento", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=255)),
                ("avg_punt_global", models.FloatField(default=0)),
                (
                    "rank_municipio",
                    models.IntegerField(
                        default=0,
                        help_text="Posición dentro de su municipio por puntaje",
                    ),
                ),
                ("demo_url", models.URLField(max_length=500)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviado", "Email enviado"),
                            ("respondio", "Respondió"),
                            ("demo", "Demo agendada"),
                            ("trial", "Trial activo"),
                            ("cliente", "Cliente pagando"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prospects",
                        to="icfes_dashboard.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospecto",
                "verbose_name_plural": "Prospectos",
                "ordering": ["municipio", "rank_municipio"],
                "unique_together": {("campaign", "email")},
            },
        ),
    ]
