# Generated by Django 5.0.3 on 2026-03-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icfes_dashboard", "0003_add_campaign_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MlAnalisisIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano_referencia", models.IntegerField()),
                ("estado", models.CharField(default="activo", max_length=20)),
                ("analisis_md", models.TextField()),
                ("shap_narrative", models.TextField(blank=True)),
                ("clusters_narrative", models.TextField(blank=True)),
                ("riesgo_narrative", models.TextField(blank=True)),
                ("oportunidad_narrative", models.TextField(blank=True)),
                (
                    "modelo_ia",
                    models.CharField(default="claude-sonnet-4-6", max_length=100),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("tokens_input", models.IntegerField(blank=True, null=True)),
                ("tokens_output", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Análisis IA - ML",
                "verbose_name_plural": "Análisis IA - ML",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["ano_referencia", "estado"],
                        name="icfes_dashb_ano_ref_29d1b8_idx",
                    )
                ],
            },
        ),
    ]
