# Generated by Django 5.0.3 on 2026-01-11 01:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_queries_per_day', models.IntegerField(help_text='Número máximo de consultas al dashboard por día')),
                ('max_export_rows', models.IntegerField(blank=True, help_text='Máximo de filas para exportación (null = ilimitado)', null=True)),
                ('api_access', models.BooleanField(default=False)),
                ('api_rate_limit', models.IntegerField(blank=True, help_text='Requests por hora (null = ilimitado)', null=True)),
                ('access_regions', models.BooleanField(default=True, help_text='Acceso a datos agregados por región')),
                ('access_departments', models.BooleanField(default=False, help_text='Acceso a datos por departamento')),
                ('access_municipalities', models.BooleanField(default=False, help_text='Acceso a datos por municipio')),
                ('access_schools', models.BooleanField(default=False, help_text='Acceso a datos de colegios individuales')),
                ('years_of_data', models.IntegerField(default=3, help_text='Años de datos históricos disponibles')),
                ('export_csv', models.BooleanField(default=False)),
                ('export_excel', models.BooleanField(default=False)),
                ('export_pdf', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Null = suscripción activa indefinidamente', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('queries_today', models.IntegerField(default=0)),
                ('last_query_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code de la respuesta', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='users_query_user_id_fa4908_idx'), models.Index(fields=['endpoint', '-timestamp'], name='users_query_endpoin_7c63b5_idx')],
            },
        ),
    ]
