# Generated by Django 5.0.3 on 2026-02-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_subscriptionplan_usersubscription_querylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
