# Generated by Django 5.0.3 on 2026-02-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="wompi_payment_method_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="wompi_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
