# Generated by Django 5.0.3 on 2026-02-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_fix_missing_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_monthly",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
