# Generated by Django 5.0.3 on 2026-02-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_subscriptionplan_price_monthly"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="Opcional, para usuarios institucionales",
                max_length=255,
                verbose_name="Nombre de Institución/Empresa",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parent", "Padre/Tutor de Estudiante"),
                    ("principal", "Rector/Director de Colegio"),
                    ("teacher", "Docente/Coordinador Académico"),
                    ("government", "Entidad Pública Educativa"),
                    ("researcher", "Investigador/Académico"),
                    ("preicfes", "Empresa de Preparación Pre-ICFES"),
                    ("language_academy", "Academia de Idiomas"),
                    ("consultant", "Consultoría Educativa"),
                    ("student", "Estudiante"),
                ],
                help_text="¿Cómo planeas usar esta plataforma?",
                max_length=50,
                verbose_name="Tipo de Usuario",
            ),
        ),
    ]
