# Generated by Django 5.0.3 on 2026-02-10 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_organization_name_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1940),
                    django.core.validators.MaxValueValidator(2015),
                ],
                verbose_name="Año de Nacimiento",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Departamento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nombre(s)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("O", "Otro"),
                    ("N", "Prefiero no decir"),
                ],
                max_length=1,
                verbose_name="Sexo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Apellido(s)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="municipality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Municipio"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Teléfono/Celular"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school_code",
            field=models.CharField(
                blank=True,
                help_text="Código DANE del colegio",
                max_length=20,
                verbose_name="Código DANE",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre del Colegio"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre de tu institución o empresa (opcional)",
                max_length=255,
                verbose_name="Nombre de Organización",
            ),
        ),
    ]
