# Generated by Django 5.0.3 on 2026-02-22 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_birth_year_user_department_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitacionEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("nombre_destinatario", models.CharField(blank=True, max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rector", "Rector / Director de colegio"),
                            ("supervisor", "Supervisor / Secretaría de Educación"),
                            (
                                "institucional",
                                "Institucional / Ministerio / Entidad gubernamental",
                            ),
                            ("padre", "Padre de Familia"),
                            ("conocido", "Conocido Personal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "colegio_nombre",
                    models.CharField(
                        blank=True,
                        help_text="Para rector/padre: personaliza el email con el nombre del colegio",
                        max_length=300,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="enviado", max_length=20)),
                ("error_msg", models.TextField(blank=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación Email",
                "verbose_name_plural": "Invitaciones Email",
                "ordering": ["-fecha_envio"],
            },
        ),
    ]
