# Generated by Django 5.0.3 on 2026-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_seed_subscription_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="last_billing_date",
            field=models.DateField(
                blank=True, help_text="Último cobro exitoso recurrente", null=True
            ),
        ),
    ]
